### ISSUE TITLE
Jisho-lens crash when take a picture or scan image from gallery

### ISSUE THREAD

**Issue by wanhuz** [elianiva/jisho-lens#2]
**Problem**

Jisho-lens app kept crashing when taking a picture or scanning any image from gallery.
Tested on Lenovo Legion Y700 tablet and Poco X3 NFC phone so I'm kinda sure this isn't device specific issue.

**Steps to reproduce**

1. Install Jisho-lens 1.1.0
2. Import database from latest release of 1.1.0
3. Scan any image from gallery or take any snapshots.
4. App will crash.

This issue didn't happen on version 1.0.1 on both my phone and tablet.

Fortunately, my phone managed to logs the issue, though I'm not sure if this is helpful:

> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/mlkit/vision/text/japanese/JapaneseTextRecognizerOptions$Builder;
> 	at c2.d.i(Unknown Source:42)
> 	at c2.d.h(Unknown Source:35)
> 	at c2.d.a(Unknown Source:33)
> 	at v2.k$a.a(Unknown Source:17)
> 	at i2.c.l(Unknown Source:18)
> 	at i2.c.m(Unknown Source:40)
> 	at i2.c.i(Unknown Source:0)
> 	at i2.b.run(Unknown Source:12)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:210)
> 	at android.os.Looper.loop(Looper.java:299)
> 	at android.app.ActivityThread.main(ActivityThread.java:8319)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)
> Caused by: java.lang.ClassNotFoundException: com.google.mlkit.vision.text.japanese.JapaneseTextRecognizerOptions$Builder
> 	... 16 more

**Comment by elianiva** [comment]
thank you for the report (and kindly providing the log :)
will look into it

**Comment by tellybobah** [comment]
Super project, I tried forking and building the app. I keep running into issues with iOS ? with the new flutter version
